services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 7aKF^bH9LG&3QpXV
      MYSQL_DATABASE: event_management_system
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  tomcat:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=event_management_system
      - DB_USER=root
      - DB_PASS=7aKF^bH9LG&3QpXV

volumes:
  db_data: